### ISSUE TITLE
Broken index.js, missing babel helper

### ISSUE THREAD

**Issue by tomaszwawrzyniakit** [A11yance/aria-query#143]
I have a problem with this library.
Index.js requires **@babel/runtime-corejs3/helpers/interopRequireDefault** but in current version of  **babel/runtime-corejs3** there is no such file.

`
"use strict";

var _interopRequireDefault = require("@babel/runtime-corejs3/helpers/interopRequireDefault");

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");

_Object$defineProperty(exports, "__esModule", {
  value: true
});

exports.roleElements = exports.elementRoles = exports.roles = exports.dom = exports.aria = void 0;

var _ariaPropsMap = _interopRequireDefault(require("./ariaPropsMap"));

var _domMap = _interopRequireDefault(require("./domMap"));

var _rolesMap = _interopRequireDefault(require("./rolesMap"));

var _elementRoleMap = _interopRequireDefault(require("./elementRoleMap"));

var _roleElementMap = _interopRequireDefault(require("./roleElementMap"));

var aria = _ariaPropsMap.default;
exports.aria = aria;
var dom = _domMap.default;
exports.dom = dom;
var roles = _rolesMap.default;
exports.roles = roles;
var elementRoles = _elementRoleMap.default;
exports.elementRoles = elementRoles;
var roleElements = _roleElementMap.default;
exports.roleElements = roleElements;
`

Currently  **aria-query** uses ` "@babel/runtime-corejs3": "^7.10.2"`  but there is no file with the name **interopRequireDefault**  even no **helpers**  directory:
https://github.com/babel/babel/tree/v7.10.2/packages/runtime-corejs3/helpers

**Comment by eps1lon** [comment]
The source code is not relevant here. In the deployed code the file exists: https://unpkg.com/@babel/runtime-corejs3@7.13.10/helpers/interopRequireDefault.js

It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox, a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by tomaszwawrzyniakit** [comment]
Ok thanks for  support, i analysed other babel versions.
Thats a problem with babel 7.12.17, accidental no files in this version  https://unpkg.com/@babel/runtime-corejs3@7.12.17/helpers/interopRequireDefault.js
