### ISSUE TITLE
Support for menu role

### ISSUE THREAD

**Issue by silverhero13** [A11yance/aria-query#150]
Hello.

WAI-ARIA has specified the menu role https://www.w3.org/TR/wai-aria-1.2/#menu. However, I noticed that the menu role is currently unsupported in this project.

It would be good if it gets added in here.

**Comment by eps1lon** [comment]
Thanks for the report.

> However, I noticed that the menu role is currently unsupported in this project.

Could you clarify what you mean by that? The role does exists right now: 

```js
import { roles } from "aria-query";

console.log(roles.get("menu"));
```
-- https://codesandbox.io/s/nervous-dew-bwlzh?file=/src/index.js:0-68

**Comment by jessebeach** [comment]
@silverhero13, @eps1lon shows that the `menu` role is supported. If you think this is not the case for a scenario you can show, please reopen the issue.
