### ISSUE TITLE
Support for SVG implicit role 

### ISSUE THREAD

**Issue by PaulSearcy** [A11yance/aria-query#181]
Coming from a downstream package (testing-library) to make a request to add the implicit role, **graphics-document**, for svgs.

https://www.w3.org/TR/html-aria/#docconformance

Just a little thing, not a big deal. I'm also going to take a look into the code here to see if it's feasible for me to make a PR!

**Comment by jessebeach** [comment]
@PaulSearcy I'm not opposed at all. You'll want to introduce a new directory -- `svg` -- into the `src/etc/roles` directory for these roles: https://github.com/A11yance/aria-query/tree/main/src/etc/roles

You can add an `else if` here: https://github.com/A11yance/aria-query/blob/29d5fb2e8f9ff8b5508ad6643a44b5cd8d6e29a5/scripts/breakUpAriaJSON.js#L246 to parse the `graphics-` roles into their own directory.

Run this script to parse the [JSON file](https://github.com/A11yance/aria-query/blob/main/scripts/roles.json) that holds all the role definitions to create the etc directory output:

```
node ./scripts/breakUpAriaJSON.js
```

You'll end up hand-writing a lot of information into https://github.com/A11yance/aria-query/blob/main/scripts/roles.json, then running that script to create the src files. I'm happy to review an in-progress PR to let you know if you're headed in the right direction.

**Comment by raszi** [comment]
It would be great if you could add this. W3C was added to the ARIA semantics in February 2021:

https://github.com/w3c/html-aria/commit/4f246657493a1ecd87e762b17fffb3a09b919a13

**Comment by jlp-craigmorten** [comment]
Unfortunately neither #338 nor #444 fully resolved the OP.

Although these changes added the graphics roles to `aria-query`, the implicit role of `graphics-document` was not associated to the HTML `<svg>` element via the `relatedConcepts` (or any other property) meaning the likes of `@testing-library/dom` are unable to derive the implicit role for `<svg>` elements.

---

There is a larger can of worms that is supporting the full set of implicit roles for SVG elements as set out by https://www.w3.org/TR/svg-aam-1.0/#mapping_role_table, but that firmly feels like a separate issue that needs some thought given the number of outstanding issues and WIP status of the SVG-AAM specification.
