### ISSUE TITLE
Enrich property info

### ISSUE THREAD

**Issue by vhfmag** [A11yance/aria-query#19]
I was wondering if information like type (property/state), short and long descriptions, and value information (type, description of behavior for each value, default value, etc) could be added to the property model. It would be very useful and I would be happy to work in a PR!

**Comment by jessebeach** [comment]
@vhfmag sure, I'm never opposed to an improvement. Go ahead and propose a low-fidelity mockup of the output you'd like -- just a paste of output is fine -- before you dig into the code, so we can agree on the details.

I'll close this for now, so I can track open issues that need my immediate attention. Go ahead and reopen it if you plan to proceed.
