### ISSUE TITLE
aria-valuenow on role separator causes warning

### ISSUE THREAD

**Issue by hzhu** [A11yance/aria-query#230]
I noticed that a `role="separator"` element with the attribute `aria-valuenow` shows a warning:

<img width="763" alt="Screen Shot 2021-09-18 at 6 47 13 PM" src="https://user-images.githubusercontent.com/1811365/133912871-32d8e4c7-dac6-4bf8-baf5-2aac32cbab06.png">

However, according to ARIA 1.2, the `aria-valuenow` is a supported attribute on an element with `role="separator"`. See:

1) https://www.w3.org/TR/wai-aria-1.1/#separator
2) https://www.w3.org/TR/wai-aria-1.1/#aria-valuenow

Should `aria-valuenow` be added to the separator's [prop list](https://github.com/A11yance/aria-query/blob/main/scripts/roles.json#L4937)?

**Comment by jessebeach** [comment]
A fix is committed. I'm working on a release but it will take some time to weave it into the eslint-plugin-jsx-a11y project.

**Comment by hzhu** [comment]
I see the fix in https://github.com/A11yance/aria-query/commit/cd57f86c963a893fa8d72f5bb37adf740a8507d0. Thanks!
