### ISSUE TITLE
elementRoles: related concepts vs. implicit semantics

### ISSUE THREAD

**Issue by eps1lon** [A11yance/aria-query#24]
Currently a `<select />` element will be mapped to the `listbox` and `combobox` role. This does not match the table of *default implicit ARIA semantics: https://www.w3.org/TR/html-aria/#el-select. It should map to either one depending on size/multiple.

It seems like the map is generated from related concepts but I think those aren't necessarily equivalent. Or the html spec is incomplete.

**Comment by HarrisonB** [comment]
If I'm reading this issue correctly, it  seems like there is a similar problem with `<input type="file">`, [which is treated as a `textbox`](https://github.com/A11yance/aria-query/blob/master/src/etc/roles/literal/textboxRole.js#L34-L38), [while the spec seems to state that there is no corresponding aria role](https://www.w3.org/TR/html-aria/#el-input-file).

**Comment by jessebeach** [comment]
@eps1lon #32 should address the issue of `<select />` mapping indiscriminately to `listbox` and `combobox`.

**Comment by eps1lon** [comment]
> @eps1lon #32 should address the issue of `<select />` mapping indiscriminately to `listbox` and `combobox`.

I'll check it out tomorrow and see if that helped. Seems like I have to check other PRs as well and update the TS types anyway.

**Comment by jessebeach** [comment]
@eps1lon I'm going to run though all of https://www.w3.org/TR/html-aria/#el-input-file right now and make the code match the spec.

**Comment by jessebeach** [comment]
Closing. Reopen if further discussion is needed.
