### ISSUE TITLE
Discussing the new "constraints" in the HTML / ARIA mapping types

### ISSUE THREAD

**Issue by jessebeach** [A11yance/aria-query#37]
From @eps1lon 

>In flow/aria.js:

```
};

 type ARIARoleRelationConceptAttribute = {
   name: string,
   value?: string | number,
   // Make these explicit. These values represent quirks of the mapping betweent
   // ARIA and other semantic ontological systems.
 -  constraints?: Array<'unset' | 'isset' | '>1'>,
 +  constraints?: Array<
 +    'undefined' // The attribute does not exist on the node: <a>
 +    | 'set' // The attribute has a value: <a b="c">
 This is confusing to me. It sounds like this should not match empty attribute values e.g. <input > type="text" list="" /> should not be considered a combobox since the list attribute has no value.
 ```

> On the other hand set would imply to me that the attribute is simply "set". It doesn't make a statement about the type of the value e.g. does it have any value or a certain value etc.

> Compare this to a <select /> element and its multiple attribute. The wording is the same select (with a multiple [...] vs input type=text [...] with a list attribute but for combobox we constrain the attribute to set and leave the multiple attribute unconstrained for listbox.

> The current implementation recognizes <select multiple="" /> as a listbox but <input type="text" list="" /> is not considered a combobox.

> I could not find statements about existence of a value in html-aria. Is it fair to assume that these constraints should be ignored when mapping html to aria (since it contains a comment about quirks in other systems)?

**Comment by jessebeach** [comment]
It's true that with only the concepts `undefined` and `set` as constraints on the attributes, the following would not be considered a valid combobox:

```
<input type="text" list="" />
```

@eps1lon, Instead of `set` as the constraint, what about `defined`, which would cover both cases below:

```
<input type="text" list="" />
<input type="text" list="js_1" />
```

Where the `list` attribute has no assigned value in the first line and and assigned DOM ID value of `js_1` in the second line.

**Comment by eps1lon** [comment]
> It's true that with only the concepts `undefined` and `set` as constraints on the attributes, the following would not be considered a valid combobox:
> 
> ```
> <input type="text" list="" />
> ```

I'd first like to clarify why that is. As far as I can tell the html-aria spec does not have a notion of defined vs. undefined. I can only find references to "with a [...] attribute". In other words why is `<input type="text" list="" />` not a `combobox` while `<select multiple="" />` is a `listbox`?

IMO the spec should explicitly state that the attribute has to be valid (see https://github.com/w3c/html-aria/issues/194) i.e. the attribute must have an ID of a `datalist` element. Otherwise this library shouldn't be opinionated about constraints.

Currently the accessibility view in chrome devtools won't classify an `<input type="text" list="non-existing-id" />` as a `combobox` either.

**Comment by eps1lon** [comment]
Considering https://github.com/w3c/html-aria/issues/194#issuecomment-560421574 I would remove the constrain and imply valid usage of the attributes i.e. `<input type="text" list="js_1" />` would only have the `combobox` role if the document contains a `datalist ` with the id `js_1`.

**Comment by jessebeach** [comment]
> I would remove the constrain and imply valid usage of the attributes i.e. <input type="text" list="js_1" /> would only have the combobox role if the document contains a datalist with the id js_1.

@eps1lon I can write this in prose as a constraint, but it would be up to an implementor to interpret and apply the constraint in practice. This module is not evaluative, just informative. Sound good?

**Comment by eps1lon** [comment]
> I can write this in prose as a constraint

Depends what the goal of this library is. If it's just mapping then I'd leave this to implementors/html spec folks. IMO implying valid attributes is a fair assumption to make.

I would only list constraints if these are unique to html-aria e.g. "size greater than 1"

**Comment by eps1lon** [comment]
Kind of forgot about this issue. I'm currently ignoring the `set` constraint anyway because I just look at the existence of the `undefined` constraint. If that doesn't exist the attribute has to be set or rather be "valid" (see https://github.com/w3c/html-aria/issues/194#issuecomment-560421574).

**Comment by jessebeach** [comment]
Still thinking about this, but status quo feels acceptable for now.
