### ISSUE TITLE
Missing mark role

### ISSUE THREAD

**Issue by amlehman** [A11yance/aria-query#385]
Hi, I'm using this library via @testing-library/react to select elements and I've found that the mark role is not included:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/mark_role
https://github.com/A11yance/aria-query/blob/main/src/etc/roles/ariaLiteralRoles.js#L124

**Comment by nschonni** [comment]
I'm not sure if any of the 1.3 stuff has been added here since it's not finalized https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/mark_role#specifications

**Comment by jessebeach** [comment]
@nschonni that's right. The 1.3 spec should be finalized soon. Probably before the end of 2022.

**Comment by jessebeach** [comment]
Closing for now. We'll get the full update when the 1.3 spec if released.

**Comment by jessebeach** [comment]
Thank you for the interest in the project @amlehman!
