### ISSUE TITLE
Copyright Attribution

### ISSUE THREAD

**Issue by rramasam** [A11yance/aria-query#40]
Hi,

Need a help. We are trying to use @testing-library/react which uses this library as nested dependency. To use "@testing-library/react" we also need to provide attribution for all the nested dependencies (as per Apache license terms). However I am not able to locate copyright statement in the repository. It will be very helpful if you can add a copyright statement in readme or in license file.

Thanks, Raja

**Comment by eps1lon** [comment]
The repository contains a [`LICENSE`](https://github.com/A11yance/aria-query/blob/master/LICENSE). The package itself also has a corresponding entry in its package.json which is [picked up by npm](https://www.npmjs.com/package/aria-query) (see license).

[The Apache 2.0 contains a copyright statement](https://github.com/A11yance/aria-query/blob/0bd0ae1796ac2502357ec48fbecec609900f0e48/LICENSE#L66).

**Comment by jessebeach** [comment]
@rramasam here's a link to the copyright attribution: https://github.com/A11yance/aria-query/blob/f951d04833e621d150e6eda951f08c7c1143681b/LICENSE#L189
