### ISSUE TITLE
Please replace dependency

### ISSUE THREAD

**Issue by Semigradsky** [A11yance/aria-query#439]
Please replace [`deep-equal`](https://www.npmjs.com/package/deep-equal) with more widespread, fast, and lightweight [`fast-deep-equal`](https://www.npmjs.com/package/fast-deep-equal).

I tried to send PR, but I am not familiar with `flow` and have issues with installing.
As I understand, it is enough to change line
https://github.com/A11yance/aria-query/blob/1f1802d5c0d401e743d661281007643a850c28d4/src/elementRoleMap.js#L5
to `import deepEqual from 'fast-deep-equal/es6';`

**Comment by jessebeach** [comment]
I appreciate the concern. I'm going to stick with deep-equal. A collaborator of mine is the author of it and it does what it needs to do well enough.

**Comment by scq** [comment]
No doubt it is well written, but it's a surprisingly heavy dependency -- installing it pulls in 50 other packages, which is a little unfortunate. The node ecosystem in general has a bit of trouble with excessive numbers of dependencies.

**Comment by thatsmydoing** [comment]
I agree, `deep-equal` does a lot of things like typed array support or map/set support that `aria-query` doesn't use. Would you accept a PR to replace the dependency with a simple deep equal utility function in this project instead?
