### ISSUE TITLE
Add role for `summary` element

### ISSUE THREAD

**Issue by maciekgrzybek** [A11yance/aria-query#44]
I've recently used dom-testing-library, that I assume uses this library under the hood. I've noticed that the default role for `summary` was missing. According to this -> https://www.w3.org/TR/html-aria/#dfn-implicit-aria-semantics  summary have `button` role by default. I'm happy to create a PR if that's correct thinking :)

**Comment by johnhunter** [comment]
Anyone know why this was closed? I have the same issue and I did not see a PR raised to close the issue.

**Comment by johnhunter** [comment]
Maybe because of this note in https://www.w3.org/TR/html-aria/#docconformance

> Many, but not all, user agents expose the summary element with an implicit ARIA role=[button](https://www.w3.org/TR/html-aria/#index-aria-button) role.

Although MDN states it has an implicit button role https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
