### ISSUE TITLE
Support for landmark roles

### ISSUE THREAD

**Issue by darekkay** [A11yance/aria-query#47]
Hello, 
as described in [this issue](https://github.com/testing-library/dom-testing-library/issues/578) from `dom-testing-library`, the `<header>` element role is not identified correctly. According to the [specs](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/banner.html), the implicit role for `<header>` is `banner`.

As noticed by @OCmilo, `aria-query` does not handle _any_ landmark roles. Is there a plan to support them? I could also have a look into this.

**Comment by darekkay** [comment]
Sorry, I should have checked the PRs in more detail first. It seems to be addressed in #46 already. Looking forward to it!

**Comment by jessebeach** [comment]
@darekkay #46 landed today. Working on a release within the next week.

**Comment by darekkay** [comment]
@jessebeach thanks for all the hard work! However, the issue is still reproducable. The [banner](https://github.com/A11yance/aria-query/blob/master/src/etc/roles/literal/bannerRole.js) role file does not include any `header` reference. It should work similar to [contentinfo](https://github.com/A11yance/aria-query/blob/master/src/etc/roles/literal/contentinfoRole.js), but with slightly different constraints:

1. The HTML `header` element defines a `banner` landmark when its context is the `body` element.
2. The HTML `header` element is not considered a `banner` landmark when it is descendant of any of following elements:
- `article`
- `aside`
- `main`
- `nav`
- `section`

Can you please re-open the issue?
