### ISSUE TITLE
Version 5.2.0 doesn't specify `deep-equal` as a dependency, but still tries to `require` it

### ISSUE THREAD

**Issue by TomerAberbach** [A11yance/aria-query#502]
Go to https://www.npmjs.com/package/aria-query?activeTab=code and then `lib/elementRoleMap.js` and you can see the transpiled file contains the following line:
```js
var _deepEqual = _interopRequireDefault(require("deep-equal"));
```

This fails because `deep-equal` isn't installed.

**Comment by gtm-nayan** [comment]
Copying over my comment from #497 

It's used on [this](https://github.com/A11yance/aria-query/blob/ef150a372812d0ba7b0dbf4f784099a6d726cad1/src/elementRoleMap.js#L27) line in the file on npm, but it's been already converted to dequal. The only reference to deep-equal I can find in this repo now is in a flow definitions file.

Building it locally gives me the correct "dequal" import.

**Comment by jessebeach** [comment]
Alright, let's get that fixed. New version inbound in a few minutes.

**Comment by jessebeach** [comment]
So weird, it's like `npm publish` didn't run `npm build`. :/

**Comment by jessebeach** [comment]
Fixed in v5.2.1

I need to investigate why `npm publish` doesn't run `npm build`.

**Comment by jessebeach** [comment]
@TomerAberbach does version v5.2.1 fix the issue for you?

**Comment by TomerAberbach** [comment]
Yup, solved for me. Thanks!
