### ISSUE TITLE
Update the NPM publish workflow so that it runs `npm run build` before pushing to the repository

### ISSUE THREAD

**Issue by jessebeach** [A11yance/aria-query#503]
In a recent release, the /lib directory wasn't updated before the version was published. This caused a removed dependency to remain in the built files, yielding a runtime error.

Follow the guide here: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

**Comment by ljharb** [comment]
Basically, add `"prepublishOnly": "npm run build"` in the scripts section in package.json.

**Comment by jessebeach** [comment]
> Basically, add `"prepublishOnly": "npm run build"` in the scripts section in package.json.

Thank you for the solution here :)
