### ISSUE TITLE
5.2.0 regression: Switch to dequal did not propagate into build

### ISSUE THREAD

**Issue by BacLuc** [A11yance/aria-query#508]
In #497 was the switch from deep-equal to dequal.
This made our build fail because the dependency was removed, but it is still used in the build.
(in the source code everything is fine)

https://unpkg.com/browse/aria-query@5.2.0/lib/elementRoleMap.js
on line 7

Change which made the build fail in our repo: https://github.com/ecamp/ecamp3/pull/3514/files#r1227772593

Failed build: https://github.com/ecamp/ecamp3/actions/runs/5250853099/jobs/9485218864?pr=3514

Error message that others find this issue:
```
 Cannot find module 'deep-equal' from 'node_modules/aria-query/lib/elementRoleMap.js'
```

**Comment by calebeby** [comment]
@BacLuc Did you see this issue? https://github.com/A11yance/aria-query/issues/502? Can you check if v5.2.1 fixed it for you?

**Comment by BacLuc** [comment]
No i did not look into the closed Issues, i did not occur to me that you are that fast.
5.2.1 fixes the issue.
I could have just waited, and the problem would have solved itself.
Thank you very much, and sorry for your time.
