### ISSUE TITLE
Image and combobox are not being detected by the getByRole.

### ISSUE THREAD

**Issue by lakshman0369** [A11yance/aria-query#512]
### Describe the bug
Image tagged element and combobox are not being detected by the getByRole query.

Aria-query previous working version - 5.1.3
Aria-query upgraded version version - 5.2.1

`<img src="/rcore/static/media/AccessDenied_Icon.db53e967.svg" alt="" class="sc-lmJFLr hLGeOl sc-jRBLiq ghkJEk" id="">`

Previously before the '**aria-query**' upgrade, getByRole query will detect the above element. But after the upgrade this query is not able to detect the above element.

We have many test cases that are breaking due to above issue . This behavior is happening since v5.2.1. Please fix the issue above issue.

**Comment by jlp-craigmorten** [comment]
R.E. the `img` role, pertinent spec snippets:

HTML element | Implicit ARIA semantics (explicitly assigning these in markup is NOT RECOMMENDED) | ARIA role, state and property allowances 
--- | --- | ---
[img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) with [alt](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-alt)="some text" | role=[img](https://www.w3.org/TR/html-aria/#index-aria-img) | Roles: [button](https://www.w3.org/TR/html-aria/#index-aria-button), [checkbox](https://www.w3.org/TR/html-aria/#index-aria-checkbox), [link](https://www.w3.org/TR/html-aria/#index-aria-link), [menuitem](https://www.w3.org/TR/html-aria/#index-aria-menuitem), [menuitemcheckbox](https://www.w3.org/TR/html-aria/#index-aria-menuitemcheckbox), [menuitemradio](https://www.w3.org/TR/html-aria/#index-aria-menuitemradio), [option](https://www.w3.org/TR/html-aria/#index-aria-option), [progressbar](https://www.w3.org/TR/html-aria/#index-aria-progressbar), [radio](https://www.w3.org/TR/html-aria/#index-aria-radio), [scrollbar](https://www.w3.org/TR/html-aria/#index-aria-scrollbar), [separator](https://www.w3.org/TR/html-aria/#index-aria-separator), [slider](https://www.w3.org/TR/html-aria/#index-aria-slider), [switch](https://www.w3.org/TR/html-aria/#index-aria-switch), [tab](https://www.w3.org/TR/html-aria/#index-aria-tab) or [treeitem](https://www.w3.org/TR/html-aria/#index-aria-treeitem). ([img](https://www.w3.org/TR/html-aria/#index-aria-img) is also allowed, but NOT RECOMMENDED.). DPub Role: [doc-cover](https://www.w3.org/TR/dpub-aria-1.0/#doc-cover).[Global aria-* attributes](https://www.w3.org/TR/wai-aria-1.2/#global_states) and any aria-* attributes applicable to the allowed roles.
[img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) with [alt](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-alt)="" | role=[presentation](https://www.w3.org/TR/html-aria/#index-aria-presentation) | [No role](https://www.w3.org/TR/html-aria/#dfn-no-role) other than [presentation](https://www.w3.org/TR/html-aria/#index-aria-presentation), which is NOT RECOMMENDED. No aria-* attributes except [aria-hidden="true"](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden).

REF: https://www.w3.org/TR/html-aria/#docconformance

It is therefore the [W3C Recommendation](https://www.w3.org/standards/types#REC) that an `img` element with an empty `alt` as given in the issue example has a `presentation` role - we should expect this lib (and RTL's `getByRole` by extension) should match that element with `getByRole("presentation")`.

**Comment by jlp-craigmorten** [comment]
See also conversation in https://github.com/testing-library/dom-testing-library/issues/1235

**Comment by jlp-craigmorten** [comment]
Test cases (with `aria-query` pinned to `5.2.1`):

```
import "react";
import "@testing-library/jest-dom";
import { render, screen } from "@testing-library/react";

describe("W3C Recommendations: https://www.w3.org/TR/html-aria/#docconformance", () => {
  test("img with no alt has an img role", async () => {
    render(<img src="#" />);

    expect(await screen.queryByRole("img")).not.toBeNull(); // Passes ✅
  });

  test("img with an empty alt has a presentation role", async () => {
    render(<img src="#" alt="" />);

    expect(await screen.queryByRole("presentation")).not.toBeNull(); // Passes ✅
  });

  test("img with a non-empty alt has an img role", async () => {
    render(<img src="#" alt="Alternative Text" />);

    expect(await screen.queryByRole("img")).not.toBeNull(); // Fails ❌
  });
});
```

**Comment by jessebeach** [comment]
@jlp-craigmorten thank you for this report. I'll look into the issue this weekend and get a fix up.
