### ISSUE TITLE
Please add `aria-description` to ariaPropsMap.js

### ISSUE THREAD

**Issue by micmcg** [A11yance/aria-query#57]
https://github.com/w3c/aria/pull/1137

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Annotations

I'm a downstream consumer of aria-query via https://github.com/jsx-eslint/eslint-plugin-jsx-a11y, which uses your ARIA props list to validate aria props in eslint. 

In my testing `aria-description` works in at least VoiceOver, probably others.

Thanks

**Comment by eps1lon** [comment]
Closing this in favor of #17 because this issue boils down to what version of the aria spec we're tracking. 

Latest release tracks 1.1 (recommended version) (or an early version of 1.2?), main branch tracks 1.2 (latest working draft).

`aria-description` is part of aria 1.3 (latest editor draft).
