### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by benmccann** [A11yance/aria-query#575]
https://github.com/A11yance/aria-query/pull/554 was merged a couple of months ago and I'd love to make use of it. Thanks!

**Comment by ljharb** [comment]
I'm waiting on #567 before cutting a release; after the outrage with axobject-query I'm not going to merge it without a stamp from one of the other maintainers, so you'll just have to wait.

**Comment by ljharb** [comment]
v5.3.1 is now released.

**Comment by benmccann** [comment]
thanks!
