### ISSUE TITLE
Support SVG roles?

### ISSUE THREAD

**Issue by lexanth** [A11yance/aria-query#72]
The SVG spec includes a list of implicit roles for SVG elements - https://www.w3.org/TR/SVG2/struct.html#implicit-aria-semantics

The SVG spec is referenced by the aria spec that this module implements for HTML. I'm not sure if you'd be open to adding a map of implicit roles for SVG elements either here or in a complementary module, but I thought it worth asking here.

**Comment by jessebeach** [comment]
@lexanth it's a great idea, but I absolutely do not have time to do it :) I'd recommend a new project in the A11yance namespace.

**Comment by jessebeach** [comment]
Closing until someone starts movement on it.
